# Generated by Django 4.0 on 2021-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(max_length=200)),
                ('dataNascimento', models.CharField(max_length=200)),
                ('rg_cpf', models.CharField(max_length=200)),
                ('contaNubank', models.CharField(max_length=200)),
                ('estadoCivil', models.CharField(max_length=200)),
                ('numeroCarteiraTrabalho', models.CharField(max_length=200)),
                ('whatsappEmail', models.CharField(max_length=200)),
                ('linkdlen', models.CharField(max_length=200)),
                ('load', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
