# Generated by Django 4.0 on 2021-12-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(max_length=200)),
                ('dataNascimento', models.IntegerField()),
                ('rg_cpf', models.TextField()),
                ('contaNubank', models.TextField()),
                ('estadoCivil', models.TextField()),
                ('numeroCarteiraTrabalho', models.TextField()),
                ('whatsappEmail', models.TextField()),
                ('linkdlen', models.TextField()),
            ],
        ),
    ]
