<<<<<<< HEAD
# Generated by Django 4.0 on 2021-12-17 01:03
=======
# Generated by Django 4.0 on 2021-12-20 21:10
>>>>>>> f52265e (codigo form)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('dataNascimento', models.IntegerField()),
=======
                ('dataNascimento', models.DateField()),
>>>>>>> f52265e (codigo form)
                ('rg_cpf', models.TextField()),
                ('contaNubank', models.TextField()),
                ('estadoCivil', models.TextField()),
                ('numeroCarteiraTrabalho', models.TextField()),
                ('whatsappEmail', models.TextField()),
                ('linkdlen', models.TextField()),
<<<<<<< HEAD
=======
                ('load', models.DateTimeField(auto_now=True)),
>>>>>>> f52265e (codigo form)
            ],
        ),
    ]
