# Generated by Django 4.0 on 2021-12-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioContratacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacao',
            name='load',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
