# Generated by Django 4.0 on 2021-12-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioContratacao', '0002_alter_contratacao_linkdlen_alter_contratacao_rg_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacao',
            name='dataNascimento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='linkdlen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='rg_cpf',
            field=models.TextField(),
        ),
    ]
